<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
    public function up(): void
    {
        Schema::create('carts', function (Blueprint $table) {
            // UUID generated by model HasUuids — no DB-level default needed
            $table->uuid('id')->primary();

            $table->uuid('user_id')->nullable();
            $table->string('session_id', 255)->nullable();

            $table->timestamp('expires_at');

            $table->timestamps();

            $table->index('user_id');
            $table->index('session_id');
            $table->index('expires_at');
        });

        Schema::table('carts', function (Blueprint $table) {
            $table->foreign('user_id')
                ->references('id')
                ->on('users')
                ->cascadeOnDelete();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('carts');
    }
};
