<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
    public function up(): void
    {
        Schema::create('blog_posts', function (Blueprint $table) {
            // UUID generated by model HasUuids — no DB-level default needed
            $table->uuid('id')->primary();

            $table->uuid('author_id')->nullable();
            $table->unsignedBigInteger('blog_category_id')->nullable();

            $table->string('title', 255);
            $table->string('slug', 255)->unique();

            $table->text('excerpt')->nullable();
            $table->longText('content');

            $table->string('featured_image', 500)->nullable();

            $table->enum('status', ['draft','published','archived'])
                ->default('draft');

            $table->timestamp('published_at')->nullable();

            $table->softDeletes();
            $table->timestamps();

            $table->index('author_id');
            $table->index('blog_category_id');
            $table->index('status');
            $table->index('published_at');
            $table->index('deleted_at');
        });

        Schema::table('blog_posts', function (Blueprint $table) {
            $table->foreign('author_id')
                ->references('id')
                ->on('users')
                ->nullOnDelete();

            $table->foreign('blog_category_id')
                ->references('id')
                ->on('blog_categories')
                ->nullOnDelete();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('blog_posts');
    }
};